### ISSUE TITLE
Facing a BUG and I think it's because of the API key. Please Help

### ISSUE THREAD

**Issue by NomanBaigA** [divyansh-dxn/WallpaperX#15]
- I tried o find a place where I can put the API key but was not able to find it. so please tell me where should I put the API key in the code. you can update your README file for this.
- If this bug is not elated to the API key tell me what is it about.
- ScreenShot Provided
![Screenshot_2023-06-02-18-14-20-22_3f6a1ca5c298a74eac90d483028ff3a1](https://github.com/divyanshdxn/WallpaperX/assets/49509445/e3033e65-0076-47ba-8a3c-7daf9a73f8e4)

**Comment by thedroiddiv** [comment]
Thanks for the suggestion, I'll add it to readme. Actually the instructions is in the local.properties.txt. The issue you faced is indeed due to missing API key, 401: Unauthorized

**Comment by NomanBaigA** [comment]
> Thanks for the suggestion, I'll add it to readme. Actually the instructions is in the local.properties.txt. The issue you faced is indeed due to missing API key, 401: Unauthorized

Thanks :)
