### ISSUE TITLE
Automate git hooks installation on build

### ISSUE THREAD

**Issue by thedroiddiv** [divyansh-dxn/WallpaperX#3]
Currently git hooks need to be installed manually by running git tasks.
Attach it to the build script so that whenever a new clone is made and build, this hooks automatically gets installed.

Note: You'll be automatically be unassigned after three days of inactivity.

**Comment by mog-rn** [comment]
@divyansh-dxn I can work on this

**Comment by thedroiddiv** [comment]
@Mogakamo go ahead

**Comment by mog-rn** [comment]
@divyansh-dxn does the repo have a CONTRIBUTING.md guide?

**Comment by mog-rn** [comment]
@divyansh-dxn could you give more details on what is supposed to be achieved in this issue because I'm having a hard time to understand what you really need. I see you have already added the task to install the git hooks for the pre-commit hook. What else is needed?

**Comment by thedroiddiv** [comment]
@Mogakamo I didn't answered earlier. Actually no, I don't have a  CONTRIBUTING.md guide for now. 

For now you need to manually run the add git hook task. I want it to be paired up with the build task. So whenever someone clones the repo, on the first build, pre-commit gets copied to .git.

**Comment by mog-rn** [comment]
ok @divyansh-dxn I am working on it

**Comment by thedroiddiv** [comment]
@Mogakamo since @sudhanshu1309 has made a successful PR first, I'm closing this issue. If you have still some additional things to add I'am happy to get it merged. I'll mark the PR for hacktoberfest as well.
