### ISSUE TITLE
Docs: WallpaperX image is missing from the Readme.

### ISSUE THREAD

**Issue by thedroiddiv** [divyansh-dxn/WallpaperX#4]
Cyrrently image is being picked from https://raw.githubusercontent.com/divyansh-dxn/WallpaperX/main/assets/icons/ic_launcher_round/android/res/mipmap-xxxhdpi/ic_launcher_round.png but it is throwing 404.

Either add it directly to the readme or add a reference link to some accesible asset.

![Screenshot 2022-10-04 at 12 28 12 PM](https://user-images.githubusercontent.com/69595691/193754730-a2467d98-49ef-4ce7-bf42-7dc8c44c642b.png)

**Comment by deepesh16b** [comment]
I can correct it
Please assign this to me
@divyansh-dxn

**Comment by jgbowser** [comment]
I just opened a PR for this several minutes ago
